import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import ReactMarkdown from "react-markdown";
import { NormalComponents } from "react-markdown/lib/complex-types";
import { SpecialComponents } from "react-markdown/lib/ast-to-react";

const mdComp: Partial<
  Omit<NormalComponents, keyof SpecialComponents> & SpecialComponents
> = {
  h1: ({ node, ...props }) => <h1 className="md-h1" {...props} />,
  h2: ({ node, ...props }) => <h2 className="md-h2" {...props} />,
  h3: ({ node, ...props }) => <h3 className="md-h3" {...props} />,
  h4: ({ node, ...props }) => <h4 className="md-h4" {...props} />,
  p: ({ node, ...props }) => <p className="md-p" {...props} />,
  hr: ({ node, ...props }) => <hr className="md-hr" {...props} />,
};

const Home: NextPage = ({ text }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline text-pink">Hello world!</h1>{" "}
        <ReactMarkdown components={mdComp} children={text} />
      </main>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async (ctx: any) => {
  console.log(ctx);
  const text = await fetch("http://localhost:3000/markdown/test.md").then(
    async (res) => {
      return await res.text();
    }
  );
  return {
    props: {
      text,
    },
  };
};
